### ISSUE TITLE
Group read in storage with no data produces panic

### ISSUE THREAD

**Issue by wolffcm** [influxdata/platform#1642]
If I enter this query:
```
from(bucket:"telegraf")
   |> range(start: -1y1m, stop: -1y)
   |> filter(fn: (r) => r._measurement == "mem" and (r._field == "active" or r._field == "available"))
   |> group(by: ["_measurement", "host"])
```
(Note: I didn't have any data that's a year old so this query should return nothing.) Then I get a panic from storage doing the group read:
```
Error: panic: runtime error: index out of range
goroutine 1011 [running]:
runtime/debug.Stack(0x1e63ee0, 0x1e53880, 0x2c67c40)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc002c2f800)
	/Users/cwolff/go/src/github.com/influxdata/flux/execute/executor.go:251 +0xbc
panic(0x1e53880, 0x2c67c40)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/platform/storage/reads.(*table).readTags(0xc000ddc000, 0xc009150090, 0x3, 0xffd)
	/Users/cwolff/go/src/github.com/influxdata/platform/storage/reads/table.go:117 +0x228
github.com/influxdata/platform/storage/reads.newIntegerGroupTable(0xc00126dd40, 0x220ab20, 0xc000574680, 0x35af2d8, 0xc0026a4a70, 0x14fc3e6c3fe7d0d8, 0x14fc3e7a382f28d8, 0x2212660, 0xc00059b350, 0xc0005777a0, ...)
	/Users/cwolff/go/src/github.com/influxdata/platform/storage/reads/table.gen.go:338 +0x2b5
github.com/influxdata/platform/storage/reads.(*tableIterator).handleGroupRead(0xc00097de00, 0xc00035eaa0, 0x21fb1c0, 0xc000574600, 0x0, 0x0)
	/Users/cwolff/go/src/github.com/influxdata/platform/storage/reads/reader.go:281 +0x45b
github.com/influxdata/platform/storage/reads.(*tableIterator).Do(0xc00097de00, 0xc00035eaa0, 0xc0003d45d0, 0x21ebe20)
	/Users/cwolff/go/src/github.com/influxdata/platform/storage/reads/reader.go:109 +0x2e8
github.com/influxdata/platform/query/functions/inputs/storage.(*source).run(0xc0012c2b40, 0x21ffd40, 0xc0003d45d0, 0xc003434c00, 0xc000554780)
	/Users/cwolff/go/src/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:105 +0xfb
github.com/influxdata/platform/query/functions/inputs/storage.(*source).Run(0xc0012c2b40, 0x21ffd40, 0xc0003d45d0)
	/Users/cwolff/go/src/github.com/influxdata/platform/query/functions/inputs/storage/storage.go:96 +0x43
github.com/influxdata/flux/execute.(*executionState).do.func1(0xc002c2f800, 0x21ffd40, 0xc0003d45d0, 0x21f2600, 0xc0012c2b40)
	/Users/cwolff/go/src/github.com/influxdata/flux/execute/executor.go:258 +0x6b
created by github.com/influxdata/flux/execute.(*executionState).do
	/Users/cwolff/go/src/github.com/influxdata/flux/execute/executor.go:239 +0x99
```

**Comment by stuartcarnie** [comment]
Closing this, which is related to influxdata/flux#319
