### ISSUE TITLE
Panic on query error and nil Result

### ISSUE THREAD

**Issue by affo** [influxdata/platform#1750]
With this, incorrect, query:

```
from(bucket:"test")
  |> influxFieldsAsCols()
  |> range(start: -1y)
```

Panics:

```
2018/12/05 15:53:21 http: panic serving [::1]:52785: runtime error: invalid memory address or nil pointer dereference
goroutine 267 [running]:
net/http.(*conn).serve.func1(0xc0001681e0)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1746 +0xd0
panic(0x1e3bf20, 0x2c3d150)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux.(*queryResultIterator).Statistics(0xc000396f90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/influxdata/flux@v0.7.5-0.20181205083114-f9026489144d/result_iterator.go:77 +0x9d
github.com/influxdata/platform/query.ProxyQueryServiceBridge.Query(0x21d16a0, 0xc000138040, 0x21e36a0, 0xc000396660, 0x341dcc8, 0xc000170620, 0xc00042bc80, 0x0, 0x0, 0x0)
	/Users/lorenzoaffetti/code/influxdata/platform/query/bridges.go:54 +0x23e
github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery(0xc000097f00, 0x21de8e0, 0xc000170620, 0xc0006b8300)
	/Users/lorenzoaffetti/code/influxdata/platform/http/query_handler.go:82 +0x314
github.com/influxdata/platform/http.(*FluxHandler).handlePostQuery-fm(0x21de8e0, 0xc000170620, 0xc0006b8300)
	/Users/lorenzoaffetti/code/influxdata/platform/http/query_handler.go:51 +0x48
net/http.HandlerFunc.ServeHTTP(0xc00039a420, 0x21de8e0, 0xc000170620, 0xc0006b8300)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1964 +0x44
github.com/julienschmidt/httprouter.(*Router).Handler.func1(0x21de8e0, 0xc000170620, 0xc0006b8200, 0x0, 0x0, 0x0)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26 +0x1c7
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc000097ec0, 0x21de8e0, 0xc000170620, 0xc0006b8200)
	/Users/lorenzoaffetti/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x792
github.com/influxdata/platform/http.(*APIHandler).ServeHTTP(0xc00014a880, 0x21de8e0, 0xc000170620, 0xc0006b8200)
	/Users/lorenzoaffetti/code/influxdata/platform/http/api_handler.go:207 +0x80f
github.com/influxdata/platform/http.(*AuthenticationHandler).ServeHTTP(0xc000096340, 0x21de8e0, 0xc000170620, 0xc0006b8100)
	/Users/lorenzoaffetti/code/influxdata/platform/http/authentication_middleware.go:90 +0x592
github.com/influxdata/platform/http.(*PlatformHandler).ServeHTTP(0xc000830920, 0x21de8e0, 0xc000170620, 0xc0006b8100)
	/Users/lorenzoaffetti/code/influxdata/platform/http/platform_handler.go:59 +0xb5
github.com/influxdata/platform/http.(*Handler).ServeHTTP(0xc00035ab40, 0x21e1860, 0xc0001fa620, 0xc0006b8100)
	/Users/lorenzoaffetti/code/influxdata/platform/http/handler.go:166 +0x21a
net/http.serverHandler.ServeHTTP(0xc0001b1040, 0x21e1860, 0xc0001fa620, 0xc0006b8000)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001681e0, 0x21e35e0, 0xc00042a900)
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11.2/libexec/src/net/http/server.go:2851 +0x2f5
```

The problem araises here: https://github.com/influxdata/platform/blob/master/query/bridges.go#L31.

 - The `ResultIterator` is `nil` because there was an error in the query
 - The `Encoder` encodes the error
 - When writing back the error in the HTTP response, `Query` invokes `Statistics` that finds a `nil` `ResultIterator`.
 - Panic
 - Empty response back

**Comment by aanthony1243** [comment]
@e-dard   @benbjohnson  looks like it's panicking on query stats. 

```

**Comment by benbjohnson** [comment]
@aanthony1243 Yes, it just needs to add a `nil` check. I added a PR: https://github.com/influxdata/flux/pull/394
