### ISSUE TITLE
Task: retry runs is not working 

### ISSUE THREAD

**Issue by bednar** [influxdata/platform#2314]
I have an issue with retrying the run of tasks. When I trying retry the Run by HTTP endpoint: "/api/v2/tasks/0335cec6ce1ab000/runs/0335cec832dab000/retry".  The response is not successfully finished and contains the **X-Influx-Error** header with error:

```bash
panic: column _measurement:string is not of type time goroutine 18496 [running]: runtime/debug.Stack(0x0, 0x0, 0x0) 	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xb1 github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0x
```
This is caused by [FindRunByID()](https://github.com/influxdata/platform/blob/01a5eb7e77d158cf2703b6c1174f43438bfe8e96/task/backend/query_logreader.go#L147) function that will throw error with a stacktrace:
```go
panic: column _measurement:string is not of type time
goroutine 31390 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/debug/stack.go:24 +0xb1
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc000bf2240)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dispatcher.go:73 +0x12f
panic(0x24802c0, 0xc00050cc70)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1e6
github.com/influxdata/flux/execute.CheckColType(0xc0004c26a0, 0xc, 0x5, 0x6)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/table.go:1138 +0x26e
github.com/influxdata/flux/execute.(*ColListTableBuilder).checkCol(0xc000fce320, 0x0, 0x6, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/table.go:1132 +0x1d9
github.com/influxdata/flux/execute.(*ColListTableBuilder).AppendTime(0xc000fce320, 0x0, 0x1577816671a6b608, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/table.go:1061 +0x61
github.com/influxdata/flux/execute.(*ColListTableBuilder).AppendValue(0xc000fce320, 0x0, 0x296a540, 0xc000ab03a0, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/table.go:1122 +0x4ea
github.com/influxdata/flux/functions/transformations.(*MergeJoinCache).join.func1(0xc000302300, 0x7, 0x296a540, 0xc000ab03a0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/functions/transformations/join.go:862 +0x1c7
github.com/influxdata/flux/values.(*object).Range(0xc000ab0220, 0xc000ab0660)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/values/object.go:96 +0x101
github.com/influxdata/flux/functions/transformations.(*MergeJoinCache).join(0xc0005c63c0, 0xc0010765f0, 0xc0009826e0, 0x0, 0x0, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/functions/transformations/join.go:855 +0xa4f
github.com/influxdata/flux/functions/transformations.(*MergeJoinCache).ForEachWithContext.func1(0x296a900, 0xc00093a0c0, 0x247c480, 0x356e570)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/functions/transformations/join.go:603 +0x379
github.com/influxdata/flux/execute.(*GroupLookup).Range(0xc000753600, 0xc000d07ab0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/group_lookup.go:83 +0xbf
github.com/influxdata/flux/functions/transformations.(*MergeJoinCache).ForEachWithContext(0xc0005c63c0, 0xc0004e4880)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/functions/transformations/join.go:591 +0xd8
github.com/influxdata/flux/execute.(*dataset).evalTriggers(0xc0009d6460, 0xc0005981a0, 0x2473240)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dataset.go:113 +0xc6
github.com/influxdata/flux/execute.(*dataset).UpdateWatermark(0xc0009d6460, 0x1577816833aa0cb8, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dataset.go:88 +0x61
github.com/influxdata/flux/functions/transformations.(*mergeJoinTransformation).UpdateWatermark(0xc00096c800, 0x9053b552b93851a3, 0xeac8c8315eb2cea0, 0x1577816833aa0cb8, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/functions/transformations/join.go:307 +0x1b6
github.com/influxdata/flux/execute.processMessage(0x295a6e0, 0xc00096c800, 0x29472e0, 0xc000741240, 0xc000a00200, 0x0, 0x0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/transport.go:202 +0x3d1
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc000bf28a0, 0xa)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/transport.go:156 +0xcb
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/transport.go:137 +0x39
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc000bf2240, 0x29562a0, 0xc0004cc3c0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dispatcher.go:126 +0x1b5
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc000bf2240, 0x29562a0, 0xc0004cc3c0)
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dispatcher.go:80 +0x99
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/Users/bednar/go/pkg/mod/github.com/influxdata/flux@v0.12.0/execute/dispatcher.go:61 +0x8e
```

@mark-rushakoff please, can you look at this problem?

**Comment by mark-rushakoff** [comment]
Thanks for the issue @bednar. The team will look into it this week.
