### ISSUE TITLE
panic: found smaller key, this should not be possible

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#319]
From ifql created by [szibis](https://github.com/szibis) : influxdata/ifql#197  

This should be somehow better handled ?

```
2018/01/26 09:40:52 from(db:"infra").range(start:-1h, stop: -15m).window(every:1m).sum()
2018/01/26 09:40:52 {
    "operations": [
        {
            "kind": "from",
            "id": "from0",
            "spec": {
                "database": "infra",
                "hosts": null
            }
        },
        {
            "kind": "range",
            "id": "range1",
            "spec": {
                "start": "-1h0m0s",
                "stop": "-15m0s"
            }
        },
        {
            "kind": "window",
            "id": "window2",
            "spec": {
                "every": "1m0s",
                "period": "1m0s",
                "start": "0001-01-01T00:00:00Z",
                "round": "0s",
                "triggering": null
            }
        },
        {

▽
            "kind": "sum",
            "id": "sum3",
            "spec": {}
        }
    ],
    "edges": [
        {
            "parent": "from0",
            "child": "range1"
        },
        {
            "parent": "range1",
            "child": "window2"
        },
        {
            "parent": "window2",
            "child": "sum3"
        }
    ],
    "resources": {
        "priority": "high",
        "concurrency_quota": 0,
        "memory_bytes_quota": 0
    }
}
2018/01/26 09:40:52 Error iterating through results: panic: found smaller key, this should not be possible
goroutine 16 [running]:
runtime/debug.Stack(0x914340, 0x91eea0, 0xc4203750e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/ifql/query/execute.(*poolDispatcher).Start.func1.1(0xc420142230)
	/root/go/src/github.com/influxdata/ifql/query/execute/dispatcher.go:67 +0xc3
panic(0x91eea0, 0xc4203750e0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/influxdata/ifql/query/execute.(*mergedStreams).more(0xc420168240, 0x2)
	/root/go/src/github.com/influxdata/ifql/query/execute/storage.go:824 +0x1b4
github.com/influxdata/ifql/query/execute.(*storageBlock).advance(0xc42016a000, 0x2bc)
	/root/go/src/github.com/influxdata/ifql/query/execute/storage.go:539 +0x52
github.com/influxdata/ifql/query/execute.(*storageBlock).DoTime(0xc42016a000, 0xc4201a4410)
	/root/go/src/github.com/influxdata/ifql/query/execute/storage.go:500 +0xb6
github.com/influxdata/ifql/functions.(*fixedWindowTransformation).Process(0xc42022e300, 0x5b571309707f64f3, 0xd82671cf6bc9dab5, 0xc8c1c0, 0xc42016a000, 0xc420222f01, 0xc420011fc8)
	/root/go/src/github.com/influxdata/ifql/functions/window.go:175 +0x186
github.com/influxdata/ifql/query/execute.processMessage(0xc89e20, 0xc42022e300, 0xc837e0, 0xc42034b7c0, 0x3, 0x0, 0x0)
	/root/go/src/github.com/influxdata/ifql/query/execute/transport.go:197 +0x200
github.com/influxdata/ifql/query/execute.(*consecutiveTransport).processMessages(0xc42022e360, 0xa)
	/root/go/src/github.com/influxdata/ifql/query/execute/transport.go:154 +0xa1
github.com/influxdata/ifql/query/execute.(*consecutiveTransport).(github.com/influxdata/ifql/query/execute.processMessages)-fm(0xa)
	/root/go/src/github.com/influxdata/ifql/query/execute/transport.go:135 +0x34
github.com/influxdata/ifql/query/execute.(*poolDispatcher).run(0xc420142230, 0xc88060, 0xc4205a4120)
	/root/go/src/github.com/influxdata/ifql/query/execute/dispatcher.go:116 +0x4b
github.com/influxdata/ifql/query/execute.(*poolDispatcher).Start.func1(0xc420142230, 0xc88060, 0xc4205a4120)
	/root/go/src/github.com/influxdata/ifql/query/execute/dispatcher.go:70 +0x95
created by github.com/influxdata/ifql/query/execute.(*poolDispatcher).Start
	/root/go/src/github.com/influxdata/ifql/query/execute/dispatcher.go:55 +0x7e
```

**Comment by adamperlin** [comment]
@nathanielc @aanthony1243  Do you have any idea what originally triggered this panic?  It seems like the error message doesn't exist anymore in the code base, and I ran a similar test query with no problem.

**Comment by mark-rushakoff** [comment]
Closing this since the error message doesn't exist in flux anymore, and because of how old the version of flux was in the original issue.
