### ISSUE TITLE
Panic when using `max` on strings in flux

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#352]
### Stack Trace
```
panic: interface conversion: interface is nil, not execute.DoStringRowSelector
goroutine 21 [running]:
runtime/debug.Stack(0x14bba60, 0x14b9b40, 0xc42034cb80)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/platform/query/execute.(*poolDispatcher).Start.func1.1(0xc420520a50)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:67 +0xb9
panic(0x14b9b40, 0xc42034cb80)
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/influxdata/platform/query/execute.(*rowSelectorTransformation).Process.func1(0x15bff40, 0xc420218050, 0x1543801, 0xc42034cb40)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/selector.go:183 +0x258
github.com/influxdata/platform/query/execute.(*ColListBlock).Do(0xc420218050, 0xc42034cb40, 0x0, 0x0)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/block.go:602 +0x3c
github.com/influxdata/platform/query/execute.(*rowSelectorTransformation).Process(0xc4200423c0, 0x255fce4fb6a41b39, 0x928afa2d6a496c96, 0x15bc6c0, 0xc420218050, 0x1, 0x2)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/selector.go:172 +0x26b
github.com/influxdata/platform/query/execute.processMessage(0x15bc800, 0xc4200423c0, 0x15b72c0, 0xc4201be260, 0x3, 0x0, 0x0)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/transport.go:199 +0x200
github.com/influxdata/platform/query/execute.(*consecutiveTransport).processMessages(0xc420221500, 0xa)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/transport.go:156 +0xa1
github.com/influxdata/platform/query/execute.(*consecutiveTransport).(github.com/influxdata/platform/query/execute.processMessages)-fm(0xa)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/transport.go:137 +0x34
github.com/influxdata/platform/query/execute.(*poolDispatcher).run(0xc420520a50, 0x15bb280, 0xc420412b70)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:116 +0x4b
github.com/influxdata/platform/query/execute.(*poolDispatcher).Start.func1(0xc420520a50, 0x15bb280, 0xc420412b70)
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:70 +0x95
created by github.com/influxdata/platform/query/execute.(*poolDispatcher).Start
	/Users/adamperlin/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:55 +0x7e
```
### Cause
The implementation for string `max` currently isn't defined in flux. As a result,`nil` interfaces are returned as defaults (see https://github.com/influxdata/platform/blob/master/query/functions/max.go#L117), causing runtime panics. `min` is also [undefined](https://github.com/influxdata/platform/blob/master/query/functions/min.go#L117). A `nil` check before [this line](https://github.com/influxdata/platform/blob/master/query/execute/selector.go#L183) might fix the panics.

**Comment by adamperlin** [comment]
Note: addressed in #363
