### ISSUE TITLE
panic when using window() 

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/platform#54]
input data: 
```#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string,string
#partition,false,false,false,false,false,false,true,true,true,true
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host,name
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:26Z,15204688,io_time,diskio,host.local,disk0
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:36Z,15204894,io_time,diskio,host.local,disk0
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:46Z,15205102,io_time,diskio,host.local,disk0
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:56Z,15205226,io_time,diskio,host.local,disk0
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:54:06Z,15205499,io_time,diskio,host.local,disk0
,,1,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:54:16Z,15205755,io_time,diskio,host.local,disk0
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:26Z,648,io_time,diskio,host.local,disk2
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:36Z,648,io_time,diskio,host.local,disk2
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:46Z,648,io_time,diskio,host.local,disk2
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:53:56Z,648,io_time,diskio,host.local,disk2
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:54:06Z,648,io_time,diskio,host.local,disk2
,,10,2018-05-22T19:53:24.421470485Z,2018-05-22T19:54:24.421470485Z,2018-05-22T19:54:16Z,648,io_time,diskio,host.local,disk2```

query and resulting panic:  
```./influx query 'fromCSV(file:"/Users/adam/programming/go/src/github.com/influxdata/platform/query/querytest/test_cases/window.in.csv") |> range(start:2018-05-22T13:09:22.885021542Z) |> window(every:1m)'
Result: _result
panic: runtime error: index out of range
goroutine 14 [running]:
runtime/debug.Stack(0x17436c0, 0x173b360, 0x1cddda0)
    /usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/platform/query/execute.(*poolDispatcher).Start.func1.1(0xc4202dc7d0)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:67 +0xb9
panic(0x173b360, 0x1cddda0)
    /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/influxdata/platform/query/execute.(*partitionKey).Value(0xc42016f3c0, 0x4, 0xc42016f3c0, 0xc4202e2d00)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/block.go:42 +0x48
github.com/influxdata/platform/query/functions.(*fixedWindowTransformation).Process.func1(0x18c9460, 0xc4202dcaa0, 0x1, 0xc420169400)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/functions/window.go:306 +0x1b2
github.com/influxdata/platform/query/execute.(*ColListBlock).Do(0xc4202dcaa0, 0xc420169400, 0x4, 0x1)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/block.go:761 +0x3c
github.com/influxdata/platform/query/functions.(*fixedWindowTransformation).Process(0xc4202721b0, 0x255fce4fb6a41b39, 0x928afa2d6a496c96, 0x18c39c0, 0xc4202dcaa0, 0x1, 0x2)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/functions/window.go:289 +0xaae
github.com/influxdata/platform/query/execute.processMessage(0x18c4040, 0xc4202721b0, 0x18b97c0, 0xc4202e2d20, 0x0, 0x0, 0x0)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/transport.go:199 +0x200
github.com/influxdata/platform/query/execute.(*consecutiveTransport).processMessages(0xc420195320, 0xa)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/transport.go:156 +0xa1
github.com/influxdata/platform/query/execute.(*consecutiveTransport).(github.com/influxdata/platform/query/execute.processMessages)-fm(0xa)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/transport.go:137 +0x34
github.com/influxdata/platform/query/execute.(*poolDispatcher).run(0xc4202dc7d0, 0x18c1380, 0xc4202e15f0)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:116 +0x4b
github.com/influxdata/platform/query/execute.(*poolDispatcher).Start.func1(0xc4202dc7d0, 0x18c1380, 0xc4202e15f0)
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:70 +0x95
created by github.com/influxdata/platform/query/execute.(*poolDispatcher).Start
    /Users/adam/programming/go/src/github.com/influxdata/platform/query/execute/dispatcher.go:55 +0x7e```

**Comment by aanthony1243** [comment]
no longer an issue after many improvements to window
